# hu: F2.5b — Cocotb golden vector harness. A C# szimulátor
#     (CilCpu.Sim) a kanonikus aranypélda; az itteni tesztek lépésről-
#     lépésre összevetik az RTL belső jeleit (r_pc, r_sp, r_fp,
#     r_call_depth, r_arg_count, r_local_count) a C# tracer által
#     generált JSONL trace-szel.
#
#     Pipeline: Python tesztprogram (bytes) → temp .t0 fájl →
#     dotnet CilCpu.Sim.Runner.dll run --trace path → JSONL parsálás →
#     RTL futtatás cocotb-bal → step-by-step compare minden ST_DECODE
#     ciklusban.
# en: F2.5b — Cocotb golden vector harness. The C# simulator
#     (CilCpu.Sim) is the canonical golden reference; tests here
#     compare RTL internal signals (r_pc, r_sp, r_fp, r_call_depth,
#     r_arg_count, r_local_count) step-by-step against a JSONL trace
#     generated by the C# tracer.

import json
import os
import subprocess
import tempfile

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge

# hu: Importáljuk a meglévő test_core.py harness-t (reset_dut, qspi_flash_driver,
#     boot_and_run helper-eket). Ugyanabban a könyvtárban van.
# en: Import the existing test_core.py harness (reset_dut, qspi_flash_driver,
#     boot_and_run helpers). Same directory.
from test_core import (
    OP_LDC_I4_5, OP_LDC_I4_2, OP_LDC_I4_3, OP_RET, OP_ADD, OP_LDARG_0, OP_LDARG_1,
    OP_CALL,
    reset_dut,
)


# ============================================================
# hu: A C# tracer hívása — runner DLL-ből generál JSONL trace-t.
# en: Call the C# tracer — generates JSONL trace via the runner DLL.
# ============================================================

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_THIS_DIR, "..", ".."))
_RUNNER_DLL = os.path.join(
    _REPO_ROOT,
    "src", "CilCpu.Sim.Runner", "bin", "Debug", "net10.0",
    "CilCpu.Sim.Runner.dll",
)


def generate_golden_trace(program_bytes, entry_rva=0, args=None):
    """hu: A C# CilCpu.Sim.Runner-rel generál JSONL trace-t a megadott
        programra és entry RVA-ra. Visszatér a parsált entry-listával.
    en: Generates a JSONL trace via the C# CilCpu.Sim.Runner for the given
        program and entry RVA. Returns the parsed entry list."""
    if not os.path.exists(_RUNNER_DLL):
        raise FileNotFoundError(
            f"Runner DLL not found: {_RUNNER_DLL}\n"
            f"Run 'dotnet build' first."
        )

    with tempfile.NamedTemporaryFile(suffix=".t0", delete=False) as t0_file:
        t0_file.write(program_bytes)
        t0_path = t0_file.name

    trace_path = t0_path + ".jsonl"

    try:
        cmd = ["dotnet", _RUNNER_DLL, "run", t0_path, "--trace", trace_path]
        if entry_rva != 0:
            cmd.extend(["--entry", str(entry_rva)])
        if args:
            cmd.extend(["--args", ",".join(str(a) for a in args)])

        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode not in (0, 2):  # 0 = halt, 2 = trap
            raise RuntimeError(
                f"Runner failed (exit={result.returncode}):\n"
                f"stdout: {result.stdout}\nstderr: {result.stderr}"
            )

        entries = []
        with open(trace_path) as f:
            for line in f:
                line = line.strip()
                if line:
                    entries.append(json.loads(line))

        return entries
    finally:
        for p in (t0_path, trace_path):
            if os.path.exists(p):
                os.unlink(p)


# ============================================================
# hu: Golden compare — RTL futás + lépésről-lépésre összevetés.
#     Az RTL ST_DECODE = 4'd3 állapotában (1 cycle) snapshot-oljuk
#     az r_pc, r_sp, r_fp, r_call_depth, r_arg_count, r_local_count
#     jeleket, és összevetjük a trace adott step-jével.
# en: Golden compare — RTL run + step-by-step comparison. We snapshot
#     RTL signals on each ST_DECODE (4'd3) cycle and compare against
#     the trace's step.
# ============================================================

_ST_DECODE = 3


async def golden_compare(dut, code_bytes, trace_entries, boot_pc=0,
                          boot_args=None, boot_locals=0, max_cycles=200_000):
    """hu: Az RTL-t a megadott programmal indítja, és lépésről-lépésre
        összevet a megadott trace-szel.
    en: Drives the RTL with the given program and compares step-by-step
        against the given trace."""
    boot_args = boot_args or []

    await reset_dut(dut, code_bytes)

    dut.i_boot_pc.value          = boot_pc
    dut.i_boot_arg_count.value   = len(boot_args)
    dut.i_boot_local_count.value = boot_locals
    dut.i_boot_start.value       = 1
    await RisingEdge(dut.clk)
    dut.i_boot_start.value       = 0

    # hu: Args streaming
    for arg_val in boot_args:
        for _ in range(100):
            await RisingEdge(dut.clk)
            try:
                if int(dut.o_boot_arg_ready.value) == 1:
                    break
            except ValueError:
                pass
        else:
            raise TimeoutError("o_boot_arg_ready never asserted")

        dut.i_boot_arg_data.value  = arg_val & 0xFFFFFFFF
        dut.i_boot_arg_valid.value = 1
        await RisingEdge(dut.clk)
        dut.i_boot_arg_valid.value = 0

    step_idx = 0
    prev_state = -1

    for cycle in range(max_cycles):
        await RisingEdge(dut.clk)

        try:
            state = int(dut.r_state.value)
            halt  = int(dut.o_halt.value)
            trap  = int(dut.o_trap.value)
        except ValueError:
            continue

        if halt or trap:
            break

        # hu: ST_DECODE belépés (edge-detection a többszöri snapshot ellen).
        # en: Edge detection on ST_DECODE entry.
        if state == _ST_DECODE and prev_state != _ST_DECODE:
            assert step_idx < len(trace_entries), (
                f"RTL has more steps than trace ({step_idx} >= {len(trace_entries)}) "
                f"at cycle {cycle}, RTL r_pc=0x{int(dut.r_pc.value):06X}"
            )

            entry = trace_entries[step_idx]
            rtl_pc = int(dut.r_pc.value)
            rtl_sp = int(dut.r_sp.value)
            rtl_fp = int(dut.r_fp.value)
            rtl_cd = int(dut.r_call_depth.value)
            rtl_ac = int(dut.r_arg_count.value)
            rtl_lc = int(dut.r_local_count.value)

            ctx = (
                f"step {entry['step']} (cycle {cycle}): "
                f"trace pc=0x{entry['pc']:06X} sp={entry['sp']} fp={entry['fp']} "
                f"cd={entry['cd']} ac={entry['ac']} lc={entry['lc']}; "
                f"rtl pc=0x{rtl_pc:06X} sp={rtl_sp} fp={rtl_fp} "
                f"cd={rtl_cd} ac={rtl_ac} lc={rtl_lc}"
            )

            assert rtl_pc == entry["pc"], f"PC mismatch — {ctx}"
            assert rtl_sp == entry["sp"], f"SP mismatch — {ctx}"
            assert rtl_fp == entry["fp"], f"FP mismatch — {ctx}"
            assert rtl_cd == entry["cd"], f"CallDepth mismatch — {ctx}"
            assert rtl_ac == entry["ac"], f"ArgCount mismatch — {ctx}"
            assert rtl_lc == entry["lc"], f"LocalCount mismatch — {ctx}"

            step_idx += 1

        prev_state = state
    else:
        raise TimeoutError(
            f"core didn't halt or trap within {max_cycles} cycles "
            f"(matched {step_idx}/{len(trace_entries)} trace steps)"
        )

    assert step_idx == len(trace_entries), (
        f"Step count mismatch: RTL ran {step_idx} steps, trace has "
        f"{len(trace_entries)} steps"
    )


# ============================================================
# hu: Golden vector tesztek
# en: Golden vector tests
# ============================================================


@cocotb.test()
async def test_70_golden_ldc_ret(dut):
    """hu: Smoke golden compare — LDC.I4_5 + RET, 2 lépés.
        Az RTL minden ST_DECODE-jánál ellenőrizzük a 6 belső
        regisztert a C# tracer trace-szel.
    en: Smoke golden compare — LDC.I4_5 + RET, 2 steps."""
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())

    program = bytes([OP_LDC_I4_5, OP_RET])
    # hu: A header nélküli programhoz a Runner --entry kapcsoló nélkül
    #     futtat (entryRva=0), de a Runner header-t vár @0-án. Ezért
    #     header nélküli forma esetén a Tracer.Execute(byte[]) overload-ot
    #     hívjuk — a Runner-ben ezt az AEntryRva<0 jelzi. CLI-n keresztül
    #     ezt jelenleg nem támogatjuk explicit módon, ezért a smoke
    #     tesztben header-t adunk.
    # en: Use a header so the CLI Runner can drive entryRva=0.
    full_program = (
        bytes([0xFE, 0, 0, 1, 2, 0, 0, 0])  # header (arg=0, local=0, code_size=2)
        + program
    )
    trace = generate_golden_trace(full_program, entry_rva=0)

    # hu: A C# trace 2 lépést rögzít (LDC + RET), az RTL is 2 ST_DECODE-ot
    #     ad, és a 6 regiszter értéke megegyezik.
    assert len(trace) == 2, f"expected 2 trace entries, got {len(trace)}"

    # hu: Az RTL boot_pc = entry_rva + header_size = 0 + 8 = 8.
    await golden_compare(dut, full_program, trace, boot_pc=8)


@cocotb.test()
async def test_71_golden_add_2_3(dut):
    """hu: Add(2,3) golden compare. Az aritmetika trace-e:
        4 lépés (LDC2, LDC3, ADD, RET) a body-ban.
    en: Add(2,3) golden compare. Arithmetic trace: 4 steps."""
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())

    program = (
        bytes([0xFE, 0, 0, 2, 4, 0, 0, 0])     # header (arg=0, local=0, code_size=4)
        + bytes([OP_LDC_I4_2, OP_LDC_I4_3, OP_ADD, OP_RET])
    )
    trace = generate_golden_trace(program, entry_rva=0)

    assert len(trace) == 4, f"expected 4 trace entries, got {len(trace)}"
    await golden_compare(dut, program, trace, boot_pc=8)


@cocotb.test()
async def test_72_golden_call_add(dut):
    """hu: CALL/RET golden compare — Add(2,3) hívás 8 lépéssel,
        a CallDepth 1→2→1 tranzícióval. Az r_arg_count és r_local_count
        is változik a callee-be lépéskor (0 → 2 → 0).
    en: CALL/RET golden compare — Add(2,3) call, 8 steps,
        CallDepth 1→2→1, r_arg_count and r_local_count change
        on callee entry (0 → 2 → 0)."""
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())

    program = bytes([
        # @0..7: caller header (no args, no locals)
        0xFE, 0, 0, 2, 8, 0, 0, 0,
        # @8..15: caller body — LDC.I4_2, LDC.I4_3, CALL 16, RET
        OP_LDC_I4_2, OP_LDC_I4_3, OP_CALL, 0x10, 0x00, 0x00, 0x00, OP_RET,
        # @16..23: add() header (arg=2, local=0)
        0xFE, 2, 0, 2, 4, 0, 0, 0,
        # @24..27: add body — LDARG.0, LDARG.1, ADD, RET
        OP_LDARG_0, OP_LDARG_1, OP_ADD, OP_RET,
    ])
    trace = generate_golden_trace(program, entry_rva=0)

    assert len(trace) == 8, f"expected 8 trace entries, got {len(trace)}"
    await golden_compare(dut, program, trace, boot_pc=8, max_cycles=20000)
